name: Django CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  django_service:
    name: Django Service CI/CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CrudBookProject/
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install tox
          pip install coverage

      - name: Run tox for tests and coverage
        run: |
          tox -e py
          
      - name: Override Coverage Source Path for Sonar
        run: sed -i 's/\/home\/runner\/work\/CrudBookProject\/CrudBookProject\//\/github\/workspace\//g' coverage-reports/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.python.coverage.reportPaths=coverage-reports/coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
